# Generated by Django 4.2.6 on 2023-10-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_deleteuser_email_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deleteuser',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
